### ISSUE TITLE
footnote with blank first line

### ISSUE THREAD

**Issue by nschloe** [executablebooks/mdit-py-plugins#48]
### Describe the bug

The following markdown is a valid footnote:

````markdown
[^lorem]

[^lorem]:
    ipsum
````

GitHub screenshot:

![sc](https://user-images.githubusercontent.com/181628/183420829-6e108932-2963-4cf2-9330-dd4285ab69e1.png)

However, mdit parses it as if it was invalid becase the first line is empty.

(See https://github.com/executablebooks/mdformat-footnote/issues/6).

### Reproduce the bug

See above.

### List your environment

- No jupyter.

- ```
  python --version
  ```
  ```
  Python 3.10.5
  ```

- Ubuntu 22.10

**Comment by hukkin** [comment]
I suspect this is a porting issue, see https://github.com/markdown-it/markdown-it-footnote/issues/48
