### ISSUE TITLE
dollarmath_plugin `renderer` parameter does not work correctly in `0.3.4`

### ISSUE THREAD

**Issue by abidlabs** [executablebooks/mdit-py-plugins#68]
### Describe the bug

The dollarmath_plugin's `renderer` parameter does not work after upgrading to `0.3.4`. Instead of using the given renderer function to parse the LaTeX, it just returns the name of the renderer function. Here's a simple example for repro:

**In <=0.3.3**

```py
from markdown_it import MarkdownIt
md = MarkdownIt().use(dollarmath_plugin, renderer=lambda x,y:x).enable("table")

md.render("# Let's learn about $x$")
```

would produce:

```html
<h1>Let\'s learn about <span class="math inline">x</span></h1>
```

**In 0.3.4**

it produces 

```html
<h1>Let's learn about <span class="math inline"><function <lambda> at 0x7fd79cb4d940></span></h1>
```

### Reproduce the bug

See above

### List your environment

Python 3.9
Windows, Linux

### More context

We use the wonderful `markdown-it-py` and `mdit-py-plugins` packages in the open-source [Gradio library](http://gradio.dev/), where we use it to render LaTeX in machine learning demos. We'd love to continue being able to do so, so hoping this bug gets fixed. Thanks!

**Comment by chrisjsewell** [comment]
oops, thanks for pointing out @abidlabs
