### ISSUE TITLE
Admonition title syntax is not consistent with other implementation

### ISSUE THREAD

**Issue by randomstuff** [executablebooks/mdit-py-plugins#93]
### Describe the bug

**context**

The [admonition syntax](https://mdit-py-plugins.readthedocs.io/en/latest/#containers) is based on [Python Markdown](https://python-markdown.github.io/extensions/admonition/):

~~~markdown
!!! danger "Don't try this at home"
    ...
~~~

**expectation**

I would expect the quotes to be absent from the output.

**bug**

With mdit-py-plugins, the quotes are present in the output:

![image](https://github.com/executablebooks/mdit-py-plugins/assets/946727/7a1543cd-d4a3-4df4-b96a-e225965720ee)

Unexpected output generated by mdit-py-plugins (spurious quotes):

~~~html
<div class="admonition danger"> <p class="admonition-title">"Don't try this at home"</p> <p>...</p> </div>
~~~

Moreover, the [additional CSS classes](https://squidfunk.github.io/mkdocs-material/reference/admonitions/) are not supported either.

Changing the behavior might cause compatiblity issues with [markdown-it-admon](https://github.com/commenthol/markdown-it-admon) however.

**problem**

This is a problem for people migrating from Python Markdown.

### Reproduce the bug

Create markdown file with:

~~~markdown
!!! danger "Don't try this at home"
    ...
~~~

Create script

~~~python3
from markdown_it import MarkdownIt
from mdit_py_plugins.admon import admon_plugin

md_opts = {
    "html": True,
}

markdown_it_render = MarkdownIt("commonmark", md_opts).use(admon_plugin)

source = open("/dev/stdin", "rt").read()
res = markdown_it_render.render(source)
print(res)
~~~

Run:

~~~sh
python3 test.py < test.md
~~~

Output:

~~~html
<div class="admonition danger">
<p class="admonition-title">&quot;Don't try this at home&quot;</p>
<p>...</p>
</div>
~~~

### List your environment

* Python 3.11.4
* Debian Linux
* markdown-it-py==3.0.0
* mdit-py-plugins==0.4.0

**Comment by chrisjsewell** [comment]
Pinging @KyleKing (who worked on this plugin 😄 )

**Comment by KyleKing** [comment]
Thanks for reporting the bug. It may be straightforward to remove the outer quotes from the matched admonition title, and I'll separately take a look at the CSS classes since those seem pretty generic

**Comment by KyleKing** [comment]
I have a PR that should resolve the problem in: https://github.com/executablebooks/mdit-py-plugins/pull/94

I'll take a look at the classes next

**Comment by randomstuff** [comment]
For reference, here is a quick patch I made, probably redundant with yours.

**Comment by KyleKing** [comment]
Got the HTML roles too 👍🏻

@chrisjsewell #94 is ready for review. I'm happy to split off the `roles` change in a separate PR. Let me know if there is anything I can add or remove otherwise!

**Comment by randomstuff** [comment]
> Moreover, the additional CSS classes are not supported either.

Some clarifications about this point.

This is the syntax documented in [mkdocs-material](https://squidfunk.github.io/mkdocs-material/reference/admonitions/). This implementation supports multiple token after `!!!` which are translated into CSS classes.

~~~markdown
!!! info inline end "Lorem ipsum"

    Lorem ipsum dolor sit amet, consectetur
    adipiscing elit. Nulla et euismod nulla.
    Curabitur feugiat, tortor non consequat
    finibus, justo purus auctor massa, nec
    semper lorem quam in massa.
~~~

Which gives:

~~~html
<div class="admonition info inline end"> <p class="admonition-title">Lorem ipsum</p> <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit. Nulla et euismod nulla. Curabitur feugiat, tortor non consequat finibus, justo purus auctor massa, nec semper lorem quam in massa.</p> </div>
~~~

**Comment by randomstuff** [comment]
My PR attempts to provides this but introduces a breaking change for this reason.

**Comment by randomstuff** [comment]
This syntax is what is implemented in [Python Markdown](https://github.com/Python-Markdown/markdown/blob/master/markdown/extensions/admonition.py:)

~~~
>>> import re
>>> RE = re.compile(r'(?:^|\n)!!! ?([\w\-]+(?: +[\w\-]+)*)(?: +"(.*?)")? *(?:\n|$)')
>>> RE.match("!!! a b c d").groups()
('a b c d', None)
>>> RE.match('!!! a b c d   "zzzz"  ').groups()
('a b c d', 'zzzz')
~~~

**Comment by randomstuff** [comment]
Notice in particuliar how the Python-Markdown implementation handles trailing `""`:

~~~
>>> RE.match('!!! a b c d   "Note: note about "foo""  ').groups()
('a b c d', 'Note: note about "foo"')
~~~

**Comment by KyleKing** [comment]
I just saw your replies here. I think we should be able to avoid a breaking change if double quotes aren't present, but I'll need to check locally

**Comment by randomstuff** [comment]
Kindly ping. Need help on this?

**Comment by KyleKing** [comment]
The PR is done and awaiting review.

@chrisjsewell, when you have a chance, could you please review and release this change: https://github.com/executablebooks/mdit-py-plugins/pull/94?

**Comment by KyleKing** [comment]
FYI: this change will be released in the next version of `mdformat-admon` regardless of the status of the PR (https://github.com/KyleKing/mdformat-admon/commit/aa27baa06b3747f507003ea36b3392acc2a632c0)
