### ISSUE TITLE
Package on pypi.org does not include tests

### ISSUE THREAD

**Issue by pgalbraith** [executablebooks/mdit-py-plugins#97]
### Describe the bug

I'm new to python and it's packaging ecosystem ... I was expecting to find all the [tests](https://github.com/executablebooks/mdit-py-plugins/tree/master/tests) in the package that's distributed from pypi.org ... is this a reasonable expectation?

### Reproduce the bug

Download [package](https://files.pythonhosted.org/packages/b4/db/61960d68d5c39ff0dd48cb799a39ae4e297f6e9b96bf2f8da29d897fba0c/mdit_py_plugins-0.4.0.tar.gz) from pypi.org & extract.

### List your environment

x

**Comment by chrisjsewell** [comment]
I'm afraid the tests are not intended for end users, there is no guarantee they work outside of this repository and its CLI/dev setup
